[build]
  base    = "docs/"
  publish = "public/"
  command = "gatsby build --prefix-paths && mkdir -p docs/federation && mv public/* docs/federation && mv docs public/ && mv public/docs/federation/_redirects public"

